export const TABLE_ENUM = {
  KEYWORD: 0x001,
  STRICT_MODE:  0x002,
  OPERATOR: 0x004,
  PUNCTUATOR: 0x008,
  BEFORE_REGEX: 0x010
}

export const KEYWORD_TABLE = Object.assign(Object.create(null), {
  async: TABLE_ENUM.KEYWORD,
  await: TABLE_ENUM.KEYWORD,
  break: TABLE_ENUM.KEYWORD,
  catch: TABLE_ENUM.KEYWORD,
  class: TABLE_ENUM.KEYWORD,
  const: TABLE_ENUM.KEYWORD,
  continue: TABLE_ENUM.KEYWORD,
  debugger: TABLE_ENUM.KEYWORD,
  default: TABLE_ENUM.KEYWORD,
  delete: TABLE_ENUM.KEYWORD,
  enum: TABLE_ENUM.KEYWORD,
  export: TABLE_ENUM.KEYWORD,
  extends: TABLE_ENUM.KEYWORD,
  finally: TABLE_ENUM.KEYWORD,
  for: TABLE_ENUM.KEYWORD,
  function: TABLE_ENUM.KEYWORD,
  if: TABLE_ENUM.KEYWORD,
  import: TABLE_ENUM.KEYWORD,
  in: TABLE_ENUM.KEYWORD,
  instanceof: TABLE_ENUM.KEYWORD,
  let: TABLE_ENUM.KEYWORD,
  new: TABLE_ENUM.KEYWORD,
  super: TABLE_ENUM.KEYWORD,
  switch: TABLE_ENUM.KEYWORD,
  this: TABLE_ENUM.KEYWORD,
  try: TABLE_ENUM.KEYWORD,
  typeof: TABLE_ENUM.KEYWORD,
  var: TABLE_ENUM.KEYWORD,
  void: TABLE_ENUM.KEYWORD,
  while: TABLE_ENUM.KEYWORD,
  with: TABLE_ENUM.KEYWORD,
  yield: TABLE_ENUM.KEYWORD,

  // Keywords before regex
  return: TABLE_ENUM.KEYWORD | TABLE_ENUM.BEFORE_REGEX,
  do: TABLE_ENUM.KEYWORD | TABLE_ENUM.BEFORE_REGEX,
  else: TABLE_ENUM.KEYWORD | TABLE_ENUM.BEFORE_REGEX,
  case: TABLE_ENUM.KEYWORD | TABLE_ENUM.BEFORE_REGEX,
  throw: TABLE_ENUM.KEYWORD | TABLE_ENUM.BEFORE_REGEX,

  // Strict Mode
  implements: TABLE_ENUM.STRICT_MODE,
  interface: TABLE_ENUM.STRICT_MODE,
  package: TABLE_ENUM.STRICT_MODE,
  private: TABLE_ENUM.STRICT_MODE,
  protected: TABLE_ENUM.STRICT_MODE,
  public: TABLE_ENUM.STRICT_MODE,
  static: TABLE_ENUM.STRICT_MODE
});

export const PUNCTUATOR_TABLE = Object.assign(Object.create(null), {
  /**
   * Operators
   */
  // Arithmetic operators
  "+": TABLE_ENUM.OPERATOR,
  "-": TABLE_ENUM.OPERATOR,
  "*": TABLE_ENUM.OPERATOR,
  "/": TABLE_ENUM.OPERATOR,
  "%": TABLE_ENUM.OPERATOR,
  "**": TABLE_ENUM.OPERATOR,

  // Assignment operators
  "=": TABLE_ENUM.OPERATOR | TABLE_ENUM.BEFORE_REGEX,
  "+=": TABLE_ENUM.OPERATOR,
  "-=": TABLE_ENUM.OPERATOR,
  "*=": TABLE_ENUM.OPERATOR,
  "/=": TABLE_ENUM.OPERATOR,
  "%=": TABLE_ENUM.OPERATOR,
  "**=": TABLE_ENUM.OPERATOR,

  // Equality operators
  "==": TABLE_ENUM.OPERATOR,
  "===": TABLE_ENUM.OPERATOR,
  "!=": TABLE_ENUM.OPERATOR,
  "!==": TABLE_ENUM.OPERATOR,

  // Relational operators
  "<": TABLE_ENUM.OPERATOR,
  ">": TABLE_ENUM.OPERATOR,
  "<=": TABLE_ENUM.OPERATOR,
  ">=": TABLE_ENUM.OPERATOR,

  // Logical operators
  "!": TABLE_ENUM.OPERATOR,
  "&&": TABLE_ENUM.OPERATOR | TABLE_ENUM.BEFORE_REGEX,
  "||": TABLE_ENUM.OPERATOR | TABLE_ENUM.BEFORE_REGEX,
  "??": TABLE_ENUM.OPERATOR,

  // Bitwise operators
  "&": TABLE_ENUM.OPERATOR,
  "|": TABLE_ENUM.OPERATOR,
  "^": TABLE_ENUM.OPERATOR,
  "~": TABLE_ENUM.OPERATOR,
  "<<": TABLE_ENUM.OPERATOR,
  ">>": TABLE_ENUM.OPERATOR,
  ">>>": TABLE_ENUM.OPERATOR,

  // Bitwise assignment operators
  "&=": TABLE_ENUM.OPERATOR,
  "|=": TABLE_ENUM.OPERATOR,
  "^=": TABLE_ENUM.OPERATOR,
  "<<=": TABLE_ENUM.OPERATOR,
  ">>=": TABLE_ENUM.OPERATOR,
  ">>>=": TABLE_ENUM.OPERATOR,

  // Increment/Decrement operators
  "++": TABLE_ENUM.OPERATOR,
  "--": TABLE_ENUM.OPERATOR,

  // Other
  "=>": TABLE_ENUM.OPERATOR | TABLE_ENUM.BEFORE_REGEX,
  "??=": TABLE_ENUM.OPERATOR,
  "?.": TABLE_ENUM.OPERATOR,
  "?": TABLE_ENUM.OPERATOR | TABLE_ENUM.BEFORE_REGEX,

  /**
   * Punctuators
   */
  // Spread/Rest operator
  "...": TABLE_ENUM.PUNCTUATOR | TABLE_ENUM.BEFORE_REGEX,

  // Parentheses and braces
  "(": TABLE_ENUM.PUNCTUATOR | TABLE_ENUM.BEFORE_REGEX,
  ")": TABLE_ENUM.PUNCTUATOR,
  "{": TABLE_ENUM.PUNCTUATOR | TABLE_ENUM.BEFORE_REGEX,
  "}": TABLE_ENUM.PUNCTUATOR,
  "[": TABLE_ENUM.PUNCTUATOR | TABLE_ENUM.BEFORE_REGEX,
  "]": TABLE_ENUM.PUNCTUATOR,

  // Separators
  ";": TABLE_ENUM.PUNCTUATOR | TABLE_ENUM.BEFORE_REGEX,
  ",": TABLE_ENUM.PUNCTUATOR | TABLE_ENUM.BEFORE_REGEX,

  // Accessors
  ".": TABLE_ENUM.PUNCTUATOR,

  // Other
  ":": TABLE_ENUM.PUNCTUATOR | TABLE_ENUM.BEFORE_REGEX
});